### ISSUE TITLE
Import does not handle gracefully corrupted PNG images

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#543]
```
020-11-27 09:30:17,685 - root - INFO - Execute SPCommon
2020-11-27 09:30:17,687 - root - INFO - Input Param = {'steperrors': [], 'InData': '/plankton_rw/ftp_plankton/Ecotaxa_Data_to_import/AWI_Nicole/pictures.zip', 'ProjectId': '3845', 'SkipAlreadyLoadedFile': '', 'SkipObjectDuplicate': '', 'UpdateClassif': '', 'Mapping': {}, 'TaxoMap': {}, 'TotalRowCount': 0, 'TaxoFound': {}, 'UserFound': {}}
2020-11-27 09:30:17,688 - root - INFO - Start Step 1 : Data validation and preparation
2020-11-27 09:30:18,889 - root - INFO - Input Param = {'steperrors': [], 'InData': '/ecotaxa_master/temptask/task037917/unzip', 'ProjectId': '3845', 'SkipAlreadyLoadedFile': '', 'SkipObjectDuplicate': '', 'UpdateClassif': '', 'Mapping': {'obj_field': {'n01': 'length', 'n02': 'width', 'n03': 'area_px', 'n04': 'form', 'n05': 'area', 'n06': 'convexity', 'n07': 'structure', 'n08': 'graymean', 'n09': 'kurtosis', 'n10': 'skewness', 'n11': 'hu_moment_1', 'n12': 'hu_moment_2', 'n13': 'hu_moment_3', 'n14': 'hu_moment_4', 'n15': 'hu_moment_5', 'n16': 'hu_moment_6', 'n17': 'hu_moment_7', 'n18': 'fourier_descriptor_01', 'n19': 'fourier_descriptor_02', 'n20': 'fourier_descriptor_03', 'n21': 'fourier_descriptor_04', 'n22': 'fourier_descriptor_05', 'n23': 'fourier_descriptor_06', 'n24': 'fourier_descriptor_07', 'n25': 'fourier_descriptor_08', 'n26': 'fourier_descriptor_09', 'n27': 'fourier_descriptor_10', 'n28': 'index', 'n29': 'haul', 'n30': 'pressure', 'n31': 'salinity', 'n32': 'conductivity', 'n33': 'oxygen_concentration', 'n34': 'temperature_oxsens', 'n35': 'oxygen_saturation', 'n36': 'dr._haardt_fluorescence_channel_a', 'n37': 'posx', 'n38': 'posy', 'n39': 'milliseconds', 'n40': 'timestamp', 't01': 'cruise', 't02': 'station', 't03': 'manual_classification', 't04': 'zoomie_state', 't05': 'vessel_name'}, 'samples': {}, 'acquisitions': {}, 'process': {}}, 'TaxoMap': {}, 'TotalRowCount': 831, 'TaxoFound': {}, 'UserFound': {}}
2020-11-27 09:30:18,889 - root - INFO - Start Step 2 : Effective data import
2020-11-27 09:30:25,385 - root - ERROR - Unhandled SubProcess Exception 
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 75, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskimport2back.py", line 142, in SPStep1
    self.SPStep2()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskimport2back.py", line 214, in SPStep2
    api.real_import_import_real_project_id_post(self.param.ProjectId, req)
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/api/projects_api.py", line 1147, in real_import_import_real_project_id_post
    return self.real_import_import_real_project_id_post_with_http_info(project_id, import_real_req, **kwargs)  # noqa: E501
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/api/projects_api.py", line 1248, in real_import_import_real_project_id_post_with_http_info
    collection_formats=collection_formats)
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/api_client.py", line 369, in call_api
    _preload_content, _request_timeout, _host)
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/api_client.py", line 188, in __call_api
    raise e
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/api_client.py", line 185, in __call_api
    _request_timeout=_request_timeout)
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/api_client.py", line 413, in request
    body=body)
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/rest.py", line 271, in POST
    body=body)
  File "/home/ecotaxa/ecotaxa/to_back/ecotaxa_cli_py/rest.py", line 224, in request
    raise ApiException(http_resp=r)
to_back.ecotaxa_cli_py.exceptions.ApiException: (500)
Reason: Internal Server Error
HTTP response headers: HTTPHeaderDict({'date': 'Fri, 27 Nov 2020 09:30:18 GMT', 'server': 'uvicorn', 'content-length': '1664', 'content-type': 'text/plain; charset=utf-8'})
HTTP response body: 
----------- BACK-END -------------
  File "/app/main.py", line 420, in real_import
    return sce.run(current_user)
  File "/app/helpers/fastApiUtils.py", line 159, in __exit__
    raise Exception(str(exc_val)).with_traceback(exc_tb)
  File "/app/main.py", line 420, in real_import
    return sce.run(current_user)
  File "/app/API_operations/imports/Import.py", line 176, in run
    row_count = source_bundle.do_import(import_where, import_how, self.req.rowcount, self.report_progress)
  File "/app/BO/Bundle.py", line 75, in do_import
    ret = self.import_each_file(where, how, stats)
  File "/app/BO/Bundle.py", line 111, in import_each_file
    rows_for_csv = tsv_to_read.do_import(where, how, stats)
  File "/app/BO/TSVFile.py", line 183, in do_import
    self.deal_with_images(where, how, image_to_write, instead_image)
  File "/app/BO/TSVFile.py", line 542, in deal_with_images
    err = ImageBO.dimensions_and_resize(how.max_dim, where.vault, sub_path, image_to_write)
  File "/app/BO/Image.py", line 29, in dimensions_and_resize
    im.thumbnail((max_dim, max_dim))
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2289, in thumbnail
    im = self.resize(size, resample, box=box, reducing_gap=reducing_gap)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 1886, in resize
    self.load()
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFile.py", line 270, in load
    raise_ioerror(err_code)
  File "/usr/local/lib/python3.6/dist-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise OSError(message + " when reading image file")
Exception: unrecognized data stream contents when reading image file

```

**Comment by grololo06** [comment]
Fixed in 2.5.8.
