### ISSUE TITLE
Prediction potentially leaves DB in an inconsistent state thus preventing further retries

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_dev#671]
Seen on a task log today:

```
2021-05-07 09:47:23,588 - root - INFO - Chunk Db Extract 13500/41955, Classification and Db Save :  0.238 s 0.002+0.025+0.210
2021-05-07 09:47:24,365 - root - INFO - Chunk Db Extract 13600/41955, Classification and Db Save :  0.774 s 0.001+0.023+0.750
2021-05-07 09:47:24,421 - root - ERROR - Unhandled SubProcess Exception 
Traceback (most recent call last):
  File "/home/ecotaxa/ecotaxa/runtask.py", line 75, in <module>
    fct()
  File "/home/ecotaxa/ecotaxa/appli/tasks/taskclassifauto2.py", line 381, in SPStep1
    and classif_auto_when is not null """, SqlParam)
psycopg2.errors.UniqueViolation: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « objectsclassifhisto_pkey »
DETAIL:  La clé « (objid, classif_date)=(236416409, 2021-04-29 13:46:59.620372) » existe déjà.
```

It looks like the code writes the history and the new classification in separate DB transactions, so if anything fails b/w the two, the previous history prevents the whole process from restarting.

**Comment by grololo06** [comment]
One possible cause would be launching twice a prediction on same dataset.

**Comment by grololo06** [comment]
Diag SQL:
```
ecotaxa=# create temp table cantclassify as select * from objectsclassifhisto obh where exists (select 1 from obj_head obj where obj.objid = obh.objid and obj.classif_auto_when=obh.classif_date);
ecotaxa=# select distinct projid from objects where objid in (select objid from cantclassify );

```

**Comment by grololo06** [comment]
For the records, the right query is:
`ecotaxa=# create temp table cantclassify as select * from objectsclassifhisto obh where exists (select 1 from obj_head obj where classif_qual='P' and obj.objid = obh.objid and obj.classif_auto_when=obh.classif_date);`

**Comment by grololo06** [comment]
Not possible anymore due to proper storage of classifications on back-end (see commits as of today in #605)
